/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as UploadTokenRouteImport } from './routes/upload.$token'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedSubcontractorsIndexRouteImport } from './routes/_authenticated/subcontractors.index'
import { Route as AuthenticatedSubcontractorsIdRouteImport } from './routes/_authenticated/subcontractors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedSubcontractorsIndexRoute =
  AuthenticatedSubcontractorsIndexRouteImport.update({
    id: '/subcontractors/',
    path: '/subcontractors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubcontractorsIdRoute =
  AuthenticatedSubcontractorsIdRouteImport.update({
    id: '/subcontractors/$id',
    path: '/subcontractors/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload/$token': typeof UploadTokenRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/subcontractors/$id': typeof AuthenticatedSubcontractorsIdRoute
  '/subcontractors/': typeof AuthenticatedSubcontractorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload/$token': typeof UploadTokenRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/subcontractors/$id': typeof AuthenticatedSubcontractorsIdRoute
  '/subcontractors': typeof AuthenticatedSubcontractorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/upload/$token': typeof UploadTokenRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/subcontractors/$id': typeof AuthenticatedSubcontractorsIdRoute
  '/_authenticated/subcontractors/': typeof AuthenticatedSubcontractorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/invoices'
    | '/projects'
    | '/review'
    | '/settings'
    | '/upload/$token'
    | '/projects/$id'
    | '/subcontractors/$id'
    | '/subcontractors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/invoices'
    | '/projects'
    | '/review'
    | '/settings'
    | '/upload/$token'
    | '/projects/$id'
    | '/subcontractors/$id'
    | '/subcontractors'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/projects'
    | '/_authenticated/review'
    | '/_authenticated/settings'
    | '/upload/$token'
    | '/_authenticated/projects/$id'
    | '/_authenticated/subcontractors/$id'
    | '/_authenticated/subcontractors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UploadTokenRoute: typeof UploadTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/subcontractors/': {
      id: '/_authenticated/subcontractors/'
      path: '/subcontractors'
      fullPath: '/subcontractors/'
      preLoaderRoute: typeof AuthenticatedSubcontractorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subcontractors/$id': {
      id: '/_authenticated/subcontractors/$id'
      path: '/subcontractors/$id'
      fullPath: '/subcontractors/$id'
      preLoaderRoute: typeof AuthenticatedSubcontractorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubcontractorsIdRoute: typeof AuthenticatedSubcontractorsIdRoute
  AuthenticatedSubcontractorsIndexRoute: typeof AuthenticatedSubcontractorsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubcontractorsIdRoute: AuthenticatedSubcontractorsIdRoute,
  AuthenticatedSubcontractorsIndexRoute: AuthenticatedSubcontractorsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UploadTokenRoute: UploadTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
